### ISSUE TITLE
Missing donors and operating units

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#168]
@Jura some of the donors (possibly new ones) are missing in the filter list when a user search for it. For example the operating unit H70 (Bureau Policy & Prog Support) is not appearing in the list. The same way, the donor id 12333 (Swedish Environmental Protection Agency) is also not appearing in the filter as a budget source.

**Comment by Jura** [comment]
@abdulriza I found where the problem is - one more file requires update: /scripts/data/process_files/country-centroids.csv, BPPS is missing there and operating units source is not populated properly. 
As a side note - countr_donors_updated.csv file you sent me via email is breaking generators script, it seems that plenty of new line ends have been added in different places and it is a problem. Can you maybe describe what you had changed in the file and I'll try to do it myself preserving original format?

**Comment by abdulriza** [comment]
@Jura Thanks. Will have a look and get the country-centroids csv updated. 

I suspected that there should be an issue with the updated country_dodnors_updated csv. In fact I had to work with 2 different files to create the updated file and I am sure something would have gone wrong in the middle. Let me have a look at that one too and get back.

**Comment by Jura** [comment]
@abdulriza Check https://github.com/Jura/undp.github.com/tree/feature/issue-168 branch for the fix

**Comment by Jura** [comment]
Deployed
